trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  appname: 'myapp'
  environment: 'production'
  country : 'India'

steps:
  - script: |
      echo "My application is $(appname)"
      echo "My environment is $(environment)"
      echo "My country is $(country)"