trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: DisplayVariablesDev
    displayName: "Display Dev Variables"

    variables:
      - group: "dev-var"

    steps:
      - script: |
          echo "My application is $(appname)"
          echo "My environment is $(environment)"
        displayName: "Display Dev Variables"

  - job: DisplayVariablesProd
    displayName: "Display Prod Variables"

    variables:
      - group: "prod-var"

    steps:
      - script: |
          echo "My application is $(appname)"
          echo "My environment is $(environment)"
        displayName: "Display Prod Variables"