trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

stages:

  # ==========================================
  # Stage 1: Display Variables
  # ==========================================
  - stage: DisplayVariables
    displayName: "Display Variables"

    jobs:

      # Dev Job
      - job: DisplayVariablesDev
        displayName: "Display Dev Variables"

        variables:
          - group: "dev-var"

        steps:
          - script: |
              echo "My application is $(appname)"
              echo "My environment is $(environment)"
            displayName: "Display Dev Variables"


      # Prod Job
      - job: DisplayVariablesProd
        displayName: "Display Prod Variables"

        variables:
          - group: "prod-var"

        steps:
          - script: |
              echo "My application is $(appname)"
              echo "My environment is $(environment)"
            displayName: "Display Prod Variables"


  # ==========================================
  # Stage 2: Build Docker Image
  # ==========================================
  - stage: BuildDockerImage
    displayName: "Build Docker Image"

    dependsOn: DisplayVariables

    jobs:
      - job: BuildDocker
        displayName: "Build Docker Image"

        steps:

          - checkout: self
            displayName: "Checkout Source Code"

          - script: |
              docker build -t myapp:$(Build.BuildId) .
              docker tag myapp:$(Build.BuildId) docker.io/vishalgharat19/myapp:$(Build.BuildId)

              echo "Docker image built and tagged successfully."
            displayName: "Build and Tag Docker Image"

          - script: |
              echo "Docker Images:"
              docker images
            displayName: "List Docker Images"